version: '3.7'
services:
  tar_web:
    container_name: tar_web
    build: './docker/php/'
    ports:
     - "8016:80"
     - "444:443"
    volumes:
     - ./app/:/var/www/html
    links:
     - tar_db
     - db_testing

  tar_db:
    container_name: tar_db
    image: mysql:5.7
    ports:
      - "33062:3306"
    volumes:
      - tar_db_vol:/var/lib/mysql
    environment:
     - MYSQL_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=db_name

  db_testing:
    container_name: db_testing
    image: mysql:5.7
    ports:
      - "33061:3306"
    volumes:
      - db_mysql_testing_vol:/var/lib/mysql
    environment:
     - MYSQL_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=db_testing

volumes:
  tar_db_vol:
  db_mysql_testing_vol: